version: 1
services:
  - type: web
    name: nordstrom-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    autoDeploy: true
    regions:
      - oregon
